<a href="https://colab.research.google.com/github/Raf4CG/praticaNumpy/blob/main/exerc%C3%ADcio1Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercício 01 - Avaliar igualdade de vetores e seus elementos**

## A partir de dois vetores x e y:

1. Construir uma função/algoritimo para avaliar se dois vetores são iguais ou diferentes;
2. Apresentar os elementos iguais dos vetores;
3. Comparar elemento por elemento dos vetores e apresentar índices onde os valores são iguais nos dois vetores.

In [32]:
import numpy as np

In [33]:
x = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])
y = np.array([1. , 2.6 , 3. , 4. , 7. , 5.6])

In [40]:
cmp = x == y
i = 0

if(cmp.all()):
  print('Todos os elementos são iguais')
elif(cmp.any()):
  print('Alguns elementos são iguais. São eles: ')
  for e in cmp:
    if(e):
      print('%.1f'% x[i])
    i += 1

  print ('--------------')
  for e in x:
    j = np.where(e == y)
    print(j)
    if(j[0].size != 0):
      print(y[j])
else:
  print('Todos os elementos são diferentes.')

Alguns elementos são iguais. São eles: 
1.0
5.6
--------------
(array([0]),)
[1.]
(array([2]),)
[3.]
(array([1]),)
[2.6]
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([5]),)
[5.6]
